
  -  name: Installation of MySQL in  CentOS
     yum:
       name:
         - mariadb
         - mariadb-server
         - python2-PyMySQL

  -  name: Configuration of MySQL in CentOS
     template:
       src: roles/compute_sql/templates/openstack.cnf.j2
       dest: /etc/my.cnf.d/openstack.cnf

  -  name: Enable and Start MySQL in CentOS
     systemd:
       name: mariadb.service
       state: restarted
       enabled: true
