
  -  name: Installation of MariaDB and MySQL in Ubuntu
     apt:
       name:
         -  mariadb-server
         -  python3-pymysql
       state: present

  -  name: Creation of Configuration of MySQL in Ubuntu
     file:
       path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
       state: touch

  -  name: Configuration of MySQL for MariaDB in Ubuntu
     copy:
       dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
       content: |
         [mysqld]
         bind-address = 10.0.0.11
         default-storage-engine = innodb
         innodb_file_per_table = on
         max_connections = 4096
         collation-server = utf8_general_ci
         character-set-server = utf8

  -  name: Enable and Start MySQL and MariaDB in Ubuntu
     systemd:
       name: "{{ item }}"
       state: restarted
       enabled: true
     loop:
       - mysql
       - mariadb
